### ISSUE TITLE
Broken tests on Node v13

### ISSUE THREAD

**Issue by mcollina** [mcollina/mqemitter-mongodb#20]
```
⨯ support one level wildcard - match empty words      operator: fail
2020-04-23T17:57:06.387+0000 I NETWORK  [conn41] end connection 127.0.0.1:53048 (4 connections now open)
      expected: 3
2020-04-23T17:57:06.387+0000 I NETWORK  [conn44] end connection 127.0.0.1:53054 (4 connections now open)
      actual:   4
2020-04-23T17:57:06.388+0000 I NETWORK  [conn43] end connection 127.0.0.1:53052 (3 connections now open)
      stack: |-
        Error: plan != count
2020-04-23T17:57:06.389+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53056 #45 (3 connections now open)
2020-04-23T17:57:06.390+0000 I NETWORK  [conn40] end connection 127.0.0.1:53046 (2 connections now open)
            at Test.assert [as _assert] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:228:54)
            at Test.bound [as _assert] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:80:32)
            at Test.fail (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:322:10)
2020-04-23T17:57:06.391+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53058 #46 (3 connections now open)
            at Test.bound [as fail] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:80:32)
            at Test.assert [as _assert] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:314:14)
            at Test.bound [as _assert] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:80:32)
            at Test.pass (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:330:10)
2020-04-23T17:57:06.393+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53060 #47 (4 connections now open)
            at Test.bound [as pass] (/home/travis/build/mcollina/mqemitter-mongodb/node_modules/tape/lib/test.js:80:32)
            at /home/travis/build/mcollina/mqemitter-mongodb/node_modules/mqemitter/abstractTest.js:222:13
            at /home/travis/build/mcollina/mqemitter-mongodb/node_modules/mongodb/lib/utils.js:731:5
```

**Comment by mcollina** [comment]
cc @robertsLando

**Comment by mcollina** [comment]
This is just flaky.
